name: API automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    #download repo
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    - name: Setup gradelw
      run: chmod +x gradelw

    #execute test only ui automation
    - name: Execute test
      run: ./gradlew apiTest

   
